version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile-app
    container_name: laravel_app
    volumes:
      - ../app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - dbdata:/var/lib/mysql

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile-bot
    container_name: puppeteer_bot
    volumes:
      - ../bot:/usr/src/app
    depends_on:
      - app
    environment:
      - API_URL=http://nginx:80/api

volumes:
  dbdata:
