FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./bot/package*.json ./

# Install dependencies
RUN npm install

# Copy existing application directory contents
COPY ./bot ./

# Expose port (if needed)
EXPOSE 3000

# Start the bot
CMD ["node", "bot.js"]
